name: Mirror Repository

on:
  schedule:
    - cron: '0 * * * *'  # 한 시간마다 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: sunwoo1256/DrumStory
          token: ${{ secrets.GIT_PAT }}

      - name: Clone the source repository (bare)
        run: git clone --bare https://github.com/JuheeNoh123/DrumStory.git source.git

      - name: Set up remote with GIT_PAT for authentication
        run: |
          cd source.git
          git remote set-url origin https://x-access-token:${{ secrets.GIT_PAT }}@github.com/sunwoo1256/DrumStory.git

      - name: Fetch changes from the source repository
        run: |
          cd source.git
          git fetch

      - name: Check for changes and push if any
        run: |
          cd source.git
          git diff --quiet origin/main || git push --force --all https://x-access-token:${{ secrets.GIT_PAT }}@github.com/sunwoo1256/DrumStory.git
          git diff --quiet origin/main || git push --force --tags https://x-access-token:${{ secrets.GIT_PAT }}@github.com/sunwoo1256/DrumStory.git
